bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile
# Create your models here.

class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='posts', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return str(self.content[:20])

    def num_likes(self):
        return self.liked.all().count()

    def num_comments(self):
        return self.comment_set.all().count()

    class Meta:
        ordering = ('-created',)

class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)

LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model): 
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

    
    

posts/forms.py
from django import forms
from .models import Post, Comment

class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    class Meta:
        model = Post
        fields = ('content', 'image')

class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label='', 
                            widget=forms.TextInput(attrs={'placeholder': 'Add a comment...'}))
    class Meta:
        model = Comment
        fields = ('body',)

posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Post, Like
from profiles.models import Profile
from .forms import PostModelForm, CommentModelForm
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

@login_required
def post_comment_create_and_list_view(request):
    qs = Post.objects.all()
    profile = Profile.objects.get(user=request.user)

    # initials
    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_added = False

    profile = Profile.objects.get(user=request.user)

    if 'submit_p_form' in request.POST:
        print(request.POST)
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.author = profile
            instance.save()
            p_form = PostModelForm()
            post_added = True

    if 'submit_c_form' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm()


    context = {
        'qs': qs,
        'profile': profile,
        'p_form': p_form,
        'c_form': c_form,
        'post_added': post_added,
    }

    return render(request, 'posts/main.html', context)

@login_required
def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value=='Like':
                like.value='Unlike'
            else:
                like.value='Like'
        else:
            like.value='Like'

            post_obj.save()
            like.save()

        # data = {
        #     'value': like.value,
        #     'likes': post_obj.liked.all().count()
        # }

        # return JsonResponse(data, safe=False)
    return redirect('posts:main-post-view')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/confirm_del.html'
    success_url = reverse_lazy('posts:main-post-view')
    # success_url = '/posts/'

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request, 'You need to be the author of the post in order to delete it')
        return obj

class PostUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:main-post-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "You need to be the author of the post in order to update it")
            return super().form_invalid(form)
    

posts/templates/posts/confirm_del.html
{% extends 'base.html' %}

{% block title %}
delete post
{% endblock title %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                <div class='ui negative message'>
                    <div class="header">
                        {{message}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if not messages %}
        <div class="ui segment">
            <h3>Delete post?</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete the post?</p>
                <button type='submit'>Submit</button>
            </form>
        </div>
    {% endif %}

{% endblock content %}

posts/templates/posts/main.html
{% extends 'base.html' %}

{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="eleven wide column">
        {% for obj in qs %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        {% ifequal request.user obj.author.user %}
                            <a href="{% url 'posts:post-update' obj.pk %}"><button class="ui button bwhite-lg ">Update</button></a>
                            <a href="{% url 'posts:post-delete' obj.pk %}"><button class="ui button bwhite-lg ">Delete</button></a>
                        {% endifequal %}
                    </div>
                </div>
                    
                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}}> 
                {{ obj.author.user }} - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ obj.content }} </p>
                <div class="right floated">
                    <form action="{% url 'posts:like-post-view' %}" method="POST" class='like-form' id='{{obj.id}}'>
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        
                            <button type="submit" class="ui button like-btn{{obj.id}}">
                                {% if profile not in obj.liked.all %}
                                    Like
                                {% else %}
                                    Unlike
                                {% endif %}
                            </button>
                            <div class="ui grid">
                                <div class="column">
                                    <div class="like-count{{obj.id}}"> {{obj.num_likes}} </div>
                                </div>
                                <div class="column">
                                    likes
                                </div>
                            </div>
                    </form>
                </div>
                <i class="comment icon"></i>
                <span> {{ obj.num_comments }} comments</span>
            </div>
            <div class="extra content">
                <div class="mb-5">
                  
                </div>
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if obj.comment_set.all %}
                    {% for c in obj.comment_set.all %}
                    
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.body }}</div>
                        </div>
                    
                    {% endfor %}
                {% endif %}
                </div>
  
                <form action="" method="POST"class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{obj.id}}>
                    {{ c_form }}
                    <button type="submit" name="submit_c_form" class="ui primary button mt-5 w-full">Send</button>
                </form>
            </div>
        </div>


        {% endfor %}
    </div>
    <div class="five wide column">
        <div class="ui segment">
            {% if post_added %}
                <div class="ui green message">Post added</div>
            {% endif %}
            <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                {% csrf_token %}
                {{p_form}}
                <button type='submit' name="submit_p_form" class="ui positive button w-full mt-5">Send</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });

            $('.like-form').submit(function(e){
                e.preventDefault()
                
                const post_id = $(this).attr('id')
                
                const likeText = $(`.like-btn${post_id}`).text()
                const trim = $.trim(likeText)

                const url = $(this).attr('action')
                
                let res;
                const likes = $(`.like-count${post_id}`).text()
                const trimCount = parseInt(likes)
                
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id':post_id,
                    },
                    success: function(response) {
                        if(trim === 'Unlike') {
                            $(`.like-btn${post_id}`).text('Like')
                            res = trimCount - 1
                        } else {
                            $(`.like-btn${post_id}`).text('Unlike')
                            res = trimCount + 1
                        }

                        $(`.like-count${post_id}`).text(res)
                    },
                    error: function(response) {
                        console.log('error', response)
                    }
                })

            })
        });
    </script>
{% endblock scripts %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}
update post
{% endblock title %}

{% block content %}
    <div class='ui segment'>
        <h3>Update post</h3>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <button type='submit' class="ui button primary mt-5">Update</button>
        </form>
    </div>
{% endblock content %}